[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
ash = "0.37.0"
fuzzy-matcher = "0.3.7"

[target.'cfg(target_os = "linux")'.dependencies]
x11-dl = "2.20.1"

[build-dependencies]
cc = "1.0.79"
bindgen = "0.64.0"